### PR TITLE
Bump to latest 2.0 and 1.11 bugfix release

### PR DESCRIPTION
**Pull request by CloudNiner**
To address https://code.djangoproject.com/ticket/29499

### CODE REVIEW

**Comment by CloudNiner** [comment]
Ugh. Looks like all the apt-get installs of the postgresql-client package are failing, can't find the desired version. I'll dig deeper a bit later.

**Comment by hectcastro** [comment]
@rbreslow, can you please help triage this PR? We usually get emails when these releases are cut, but either they never went out or I missed it.

**Comment by CloudNiner** [comment]
Ugh, 🤦‍♂️ I missed that this is unreleased, expected Sept 1. So I'm going to close this for now.

The postgresql-client package issue is still a problem, I was able to fix it in alpine by changing to `PG_VERSION=10.5-r0`. I expect a similar bump for slim would work once this Django version is actually released.

**Comment by rbreslow** [comment]
@CloudNiner Beat me to it.

Neither of these versions have been released yet, which is why they didn't appear on our radar.

See: 
* https://docs.djangoproject.com/en/2.1/releases/1.11.16/
* https://docs.djangoproject.com/en/2.1/releases/2.0.9/

This is the updated build matrix for when we do open a PR:

```diff
diff --git a/.travis.yml b/.travis.yml
index cd3f6eb..197be25 100644
--- a/.travis.yml
+++ b/.travis.yml
@@ -2,20 +2,20 @@ language: bash
 services: docker

 env:
-  - VERSION=1.9 PYTHON_VERSION=2.7 PG_MAJOR=9.4 PG_VERSION=9.4.18-2.pgdg90+1 VARIANT=slim
-  - VERSION=1.9 PYTHON_VERSION=2.7 PG_MAJOR=10 PG_VERSION=10.4-r0 VARIANT=alpine
-  - VERSION=1.9 PYTHON_VERSION=3.5 PG_MAJOR=10 PG_VERSION=10.4-r0 VARIANT=alpine
-  - VERSION=1.10 PYTHON_VERSION=2.7 PG_MAJOR=10 PG_VERSION=10.4-2.pgdg90+1 VARIANT=slim
-  - VERSION=1.10 PYTHON_VERSION=2.7 PG_MAJOR=10 PG_VERSION=10.4-r0 VARIANT=alpine
-  - VERSION=1.10 PYTHON_VERSION=3.5 PG_MAJOR=10 PG_VERSION=10.4-r0 VARIANT=alpine
-  - VERSION=1.11 PYTHON_VERSION=2.7 PG_MAJOR=10 PG_VERSION=10.4-2.pgdg90+1 VARIANT=slim
-  - VERSION=1.11 PYTHON_VERSION=3.6 PG_MAJOR=10 PG_VERSION=10.4-2.pgdg90+1 VARIANT=slim
-  - VERSION=1.11 PYTHON_VERSION=2.7 PG_MAJOR=10 PG_VERSION=10.4-r0 VARIANT=alpine
-  - VERSION=1.11 PYTHON_VERSION=3.6 PG_MAJOR=10 PG_VERSION=10.4-r0 VARIANT=alpine
-  - VERSION=2.0 PYTHON_VERSION=3.6 PG_MAJOR=10 PG_VERSION=10.4-2.pgdg90+1 VARIANT=slim
-  - VERSION=2.0 PYTHON_VERSION=3.6 PG_MAJOR=10 PG_VERSION=10.4-r0 VARIANT=alpine
-  - VERSION=2.0 PYTHON_VERSION=3.7 PG_MAJOR=10 PG_VERSION=10.4-2.pgdg90+1 VARIANT=slim
-  - VERSION=2.0 PYTHON_VERSION=3.7 PG_MAJOR=10 PG_VERSION=10.4-r0 VARIANT=alpine
+  - VERSION=1.9 PYTHON_VERSION=2.7 PG_MAJOR=9.4 PG_VERSION=9.4.19-1.pgdg90+1 VARIANT=slim
+  - VERSION=1.9 PYTHON_VERSION=2.7 PG_MAJOR=10 PG_VERSION=10.5-r0 VARIANT=alpine
+  - VERSION=1.9 PYTHON_VERSION=3.5 PG_MAJOR=10 PG_VERSION=10.5-r0 VARIANT=alpine
+  - VERSION=1.10 PYTHON_VERSION=2.7 PG_MAJOR=10 PG_VERSION=10.5-1.pgdg90+1 VARIANT=slim
+  - VERSION=1.10 PYTHON_VERSION=2.7 PG_MAJOR=10 PG_VERSION=10.5-r0 VARIANT=alpine
+  - VERSION=1.10 PYTHON_VERSION=3.5 PG_MAJOR=10 PG_VERSION=10.5-r0 VARIANT=alpine
+  - VERSION=1.11 PYTHON_VERSION=2.7 PG_MAJOR=10 PG_VERSION=10.5-1.pgdg90+1 VARIANT=slim
+  - VERSION=1.11 PYTHON_VERSION=3.6 PG_MAJOR=10 PG_VERSION=10.5-1.pgdg90+1 VARIANT=slim
+  - VERSION=1.11 PYTHON_VERSION=2.7 PG_MAJOR=10 PG_VERSION=10.5-r0 VARIANT=alpine
+  - VERSION=1.11 PYTHON_VERSION=3.6 PG_MAJOR=10 PG_VERSION=10.5-r0 VARIANT=alpine
+  - VERSION=2.0 PYTHON_VERSION=3.6 PG_MAJOR=10 PG_VERSION=10.5-1.pgdg90+1 VARIANT=slim
+  - VERSION=2.0 PYTHON_VERSION=3.6 PG_MAJOR=10 PG_VERSION=10.5-r0 VARIANT=alpine
+  - VERSION=2.0 PYTHON_VERSION=3.7 PG_MAJOR=10 PG_VERSION=10.5-1.pgdg90+1 VARIANT=slim
+  - VERSION=2.0 PYTHON_VERSION=3.7 PG_MAJOR=10 PG_VERSION=10.5-r0 VARIANT=alpine
```

**Pull request closed without merging**
