### PR TITLE
Update django to 1.9.2

### PR DESCRIPTION
**Pull request by notthatbreezy**
Bumps to current version

### CODE REVIEW

**Comment by hectcastro** [comment]
:+1:

**Comment by CloudNiner** [comment]
`pip freeze` output on the readme is no longer correct

**Comment by CloudNiner** [comment]
Does this mean that any project that pulls this container will update to Django 1.9?

Should we consider having a `django-lts` container since 1.8 is a LTS release and 1.9 is not?
https://www.djangoproject.com/download/#supported-versions

**Comment by notthatbreezy** [comment]
As long as the projects have pinned correctly to `django:1.8.8` they should not see any negative effects

**Comment by hectcastro** [comment]
`README` example addressed in https://github.com/azavea/docker-django/commit/8ff98e6eadeea3ed83f917ef3b73b5530af5d6b0.

**Pull request merged**
