### PR TITLE
Upgrade Django to 2.2.8

### LINKED ISSUE #92: Upgrade Django to 2.2.8
> Django versions 2.2.8 and 2.1.15, together with Django 3.0 final will be released on Monday, December 2, 2019 around 1400 UTC. They will fix a security defect with severity “medium”.

See: https://travis-ci.org/azavea/docker-django/builds/608335454

### PR DESCRIPTION
**Pull request by coalkettler**
## Overview

This update contain a security patch and several bugfixes for Django 2.2. See release notes for [2.2.8](https://docs.djangoproject.com/en/2.2/releases/2.2.8/).

We have also upgraded the PostgreSQL client version to the latest available on the following image variants:

* `alpine`: `10.10-1.pgdg100+1` to `10.11-1.pgdg100+1`
* `slim`: `11.5-r0` to `11.6-r0`

For the `alpine` variant, the `gdal` package was moved from the `edge/testing` repo to the `edge/community` repo upstream. The Docker image build has been updated to account for this.

Resolves #92.

## Testing Instructions

* Confirm that [Travis build](https://travis-ci.org/azavea/docker-django/builds/620287196) passes.

### CODE REVIEW

**Comment by coalkettler** [comment]
@hectcastro @rbreslow Requesting review from both of you to get extra eyes on this. This upgrade has a few dependencies involved, especially the upstream Alpine repo change.

**Comment by rbreslow** [comment]
>For the `alpine` variant, the `gdal` package was moved from the `edge/testing` repo to the `edge/community` repo upstream. The Docker image build has been updated to account for this.

Is there anything you can link to about this? Also, cool if there aren't any docs, and you just found out by noticing the package was gone from one repo and appeared in another.

**Comment by coalkettler** [comment]
@rbreslow I haven't been able to find a ton of info, official or anecdotal, on this yet. This issue tipped me off to the move: https://github.com/appropriate/docker-postgis/issues/157

Confirmed it in the Alpine package repos: https://pkgs.alpinelinux.org/packages?name=gdal&branch=edge

**Review by hectcastro — APPROVED** [review]
Nice job handling the PostgreSQL client library updates. Changes look good. I confirmed the new location of the `gdal` package via https://pkgs.alpinelinux.org/packages. 👍

**Review by rbreslow — APPROVED** [review]
👍

**Comment by GammaGames** [comment]
@ColeKettler I had asked for help a while ago on the alpine mailing list and one of the devs had [brought up moving proj to community](https://lists.alpinelinux.org/~alpine/devel/%3C661e0b45-63ff-a180-de21-afa353f72806%40gmx.de%3E), they must've done it with a handful of other packages too. 

It might've been discussed on IRC or something after that, but that is the only mention of it I have been able to find.

**Pull request merged**
